export const EMAILCHANGED = ""
export const PASSWORDCHANGED = ""


export const ADDTOFAVORITE = 'ADDTOFAVORITE';
export const REMOVEFROMFAVORITE = 'REMOVEFROMFAVORITE';
export const ADDTOCART = 'ADDTOCART';
export const REMOVEFROMCART = 'REMOVEFROMCART';
export const INCREMENTCART = 'INCREMENTCART';
export const DECREMENTCART = 'DECREMENTCART';
export const INCREMENTHEADCART = 'INCREMENHEADTCART';
export const DECREMENTHEADCART = 'DECREMENTCARHEADT';
